import type { Recipe } from './types';

export interface PrepNotes { fresh: string[]; staples: string[]; prep: string; finish: string; swaps: string; nutrition: string }
const base = { servings: 3, difficulty: 'easy' as const, equipment: ['Stove', 'Pan'], tags: ['vegetarian', 'three-day prep'] };
const ing = (name: string, quantity: number): Recipe['ingredients'][number] => ({ name, quantity, unit: 'g' });
/** Original Pantry Pal kitchen drafts, inspired by these cuisines; not claims of traditional authenticity. */
export const prepRecipes: Recipe[] = [
  { ...base, id: 'prep-thai-basil-tofu', name: 'Thai-inspired basil tofu & cabbage', cuisine: 'Thai', minutes: 30,
    description: 'A savory tofu and cabbage skillet with a fresh basil finish. Keep the grain base separate for flexible lunches.',
    ingredients: [ing('Firm tofu', 600), ing('Raw cabbage', 450), ing('Raw carrot', 180), ing('Raw garlic', 12), ing('Olive oil', 20), ing('Soy sauce', 30), ing('Basil', 20)],
    steps: ['Drain tofu, pat dry and cut into 2 cm cubes. Thinly slice cabbage and carrots; mince garlic. Keep basil aside.', 'Heat half the oil in a wide pan over medium-high heat. Brown tofu for 8–10 minutes, turning gently. Transfer to a plate.', 'Add remaining oil, carrots and cabbage. Stir-fry 5–7 minutes; add garlic for the final minute.', 'Return tofu, add soy sauce and 3 tablespoons water. Simmer 2 minutes. Taste before adding salt; sauces vary in sodium.', 'Divide into three portions. Add torn basil to the portion being served; pack the remaining basil separately. Serve with a separately prepared grain if desired.'] },
  { ...base, id: 'prep-indian-lentil-spinach', name: 'Indian-inspired lentil & spinach dal', cuisine: 'Indian', minutes: 40,
    description: 'A gently spiced lentil pot that uses the same spinach, tomato, onion and garlic as the second prep session.',
    ingredients: [ing('Dry lentils', 240), ing('Raw spinach', 240), ing('Raw tomato', 400), ing('Raw onion', 180), ing('Raw garlic', 12), ing('Olive oil', 18), ing('Cumin', 3), ing('Turmeric', 2)],
    steps: ['Rinse lentils and remove any debris. Dice onion and tomatoes; mince garlic. Wash spinach.', 'Warm oil over medium heat. Soften onion for 6–8 minutes, then stir in garlic, cumin and turmeric for 30 seconds.', 'Add tomatoes, lentils and 800 ml water. Bring to a boil, then simmer partly covered 25–35 minutes, adding water as needed until lentils are tender.', 'Stir in spinach for 2–3 minutes. Adjust thickness with water and season to taste.', 'Portion into three shallow containers. Serve as a bowl or with a separately portioned grain; add lemon at serving if available.'] },
  { ...base, id: 'prep-nigerian-beans', name: 'Nigerian-inspired tomato beans & greens', cuisine: 'Nigerian', minutes: 35,
    description: 'An adaptable beans pot inspired by Nigerian home cooking. Use cooked beans to keep the prep session manageable.',
    ingredients: [ing('Cooked black-eyed peas', 600), ing('Raw tomato', 450), ing('Raw red bell pepper', 200), ing('Raw onion', 180), ing('Raw spinach', 200), ing('Olive oil', 24), ing('Chilli', 5)],
    steps: ['Blend or finely chop tomatoes, bell pepper, half the onion and chilli. Dice the remaining onion. Drain cooked black-eyed peas; rinse canned beans if using.', 'Heat oil in a pot. Soften diced onion for 5 minutes. Add the tomato-pepper mixture and simmer uncovered 15–20 minutes, stirring, until thickened.', 'Add cooked beans and 150 ml water. Simmer gently for 8–10 minutes; mash a small spoonful to thicken if desired.', 'Fold in spinach and cook until wilted. Taste and adjust seasoning. This version uses olive oil and spinach as practical substitutions.', 'Divide into three portions. Pair with a grain or roasted plantain prepared separately; these additions are not included in the ingredient estimate.'] },
  { ...base, id: 'prep-vietnamese-tofu', name: 'Vietnamese-inspired tomato tofu', cuisine: 'Vietnamese', minutes: 30,
    description: 'Golden tofu simmered in a light tomato sauce. Uses the same tofu, tomatoes and garlic as neighboring meals.',
    ingredients: [ing('Firm tofu', 600), ing('Raw tomato', 600), ing('Raw onion', 120), ing('Raw garlic', 12), ing('Olive oil', 20), ing('Soy sauce', 24), ing('Spring onion', 30)],
    steps: ['Drain and pat tofu dry, then cube. Chop tomatoes and onion; mince garlic. Slice spring onion, keeping the green tops aside.', 'Heat oil in a wide pan. Brown tofu over medium-high heat for 8–10 minutes; move to a plate.', 'Soften onion in the same pan for 4 minutes, adding a splash of water if it sticks. Add garlic, then tomatoes and soy sauce.', 'Simmer 8–10 minutes until tomatoes collapse. Add tofu and 100 ml water, then simmer 5 minutes so the tofu takes on the sauce.', 'Divide into three portions. Finish each serving with spring onion tops. Serve grain and crunchy vegetables separately so they keep their texture.'] },
  { ...base, id: 'prep-chickpea-quinoa', name: 'Chickpea, quinoa & crunchy cabbage bowls', cuisine: 'International', minutes: 20,
    description: 'A flexible cold bowl for the branch-out slot. Keep the dressing separate and use cabbage instead of delicate salad leaves.',
    ingredients: [ing('Cooked chickpeas', 450), ing('Cooked quinoa', 450), ing('Raw cabbage', 240), ing('Raw carrot', 180), ing('Olive oil', 18), ing('Lemon juice', 45)],
    steps: ['Use freshly cooked quinoa that has been cooled promptly, or cook following its package instructions. Weigh 450 g cooked quinoa, not dry.', 'Drain chickpeas. Finely shred washed cabbage and grate carrots.', 'Whisk lemon juice and oil with seasoning to taste. Divide the dressing between three small containers.', 'Divide quinoa, chickpeas and vegetables into three covered lunch containers. Refrigerate promptly; mix dressing in only when serving.', 'For variety, add herbs left from the other prep session. Any extra toppings change the nutrition estimate.'] },
  { ...base, id: 'prep-oats-apple', name: 'Apple, almond & oat breakfast jars', cuisine: 'International', minutes: 10, equipment: [],
    description: 'Three breakfast portions from one apple, oats and a small amount of almonds. Keep toppings separate until eating.',
    ingredients: [ing('Dry oats', 150), ing('Whole milk', 450), ing('Raw apple with skin', 180), ing('Almonds', 30)],
    steps: ['Divide oats and milk equally between three clean lidded jars. Stir, cover and refrigerate overnight.', 'Keep the whole apple refrigerated until needed; cut one third fresh for each breakfast. Chop almonds and store dry in a separate container.', 'At serving, stir the oats, add a little water if needed, and top with apple and almonds.', 'Use pasteurized milk and keep jars cold. A fortified unsweetened soy drink is a possible swap; check its label because nutrition and allergens differ.'] },
];
export const prepNotes: Record<string, PrepNotes> = {
  'prep-thai-basil-tofu': { fresh: ['Tofu', 'Cabbage', 'Carrot', 'Basil'], staples: ['Soy sauce', 'Oil', 'Garlic'], prep: 'Brown tofu once; keep basil and grain separate.', finish: 'Add basil after reheating, then a fresh squeeze of lime if you have one.', swaps: 'Use broccoli instead of cabbage if already in the fridge. Check soy sauce and curry pastes for wheat, fish or shrimp when cooking for dietary needs.', nutrition: 'Tofu contributes protein; cabbage and carrot add vegetable variety. Grain portions are optional and counted separately.' },
  'prep-indian-lentil-spinach': { fresh: ['Spinach', 'Tomato', 'Onion'], staples: ['Dry lentils', 'Cumin', 'Turmeric', 'Garlic', 'Oil'], prep: 'Cook one pot, then portion; save some spinach for the beans pot.', finish: 'Loosen with water when reheating. Finish with lemon or remaining herbs.', swaps: 'Frozen spinach works well. Different lentils need different cooking times; cook until fully tender.', nutrition: 'Lentils contribute plant protein and fiber. Weigh them dry for this recipe; cooked lentils are a different nutrition entry.' },
  'prep-nigerian-beans': { fresh: ['Tomato', 'Bell pepper', 'Onion', 'Spinach'], staples: ['Cooked or canned beans', 'Oil', 'Chilli'], prep: 'Make the pepper-tomato base while lentils simmer; portion the cooked beans separately if freezing.', finish: 'Reheat a single portion and add a freshly prepared side.', swaps: 'Cooked brown beans or black-eyed peas work. This is a vegetarian adaptation; traditional versions and household preferences vary.', nutrition: 'Beans contribute fiber and protein. Canned product labels are the best guide to sodium; rinse when appropriate.' },
  'prep-vietnamese-tofu': { fresh: ['Tofu', 'Tomato', 'Spring onion'], staples: ['Soy sauce', 'Oil', 'Garlic'], prep: 'Use the second half of the tofu shop; keep fresh spring onion tops dry and separate.', finish: 'Warm tofu in its sauce, then add the fresh garnish.', swaps: 'Use a mushroom-based vegetarian seasoning instead of fish sauce. Check the label; not every sauce is vegetarian.', nutrition: 'Firm tofu brands vary in protein and calcium. Use the package label for a closer estimate.' },
  'prep-chickpea-quinoa': { fresh: ['Cabbage', 'Carrot', 'Lemon'], staples: ['Chickpeas', 'Quinoa', 'Oil'], prep: 'Use the remaining sturdy vegetables; keep dressing separate.', finish: 'Mix just before eating for a crisp texture.', swaps: 'Cooked lentils can replace chickpeas. Keep the cooked grain weight the same, but expect different nutrition.', nutrition: 'Chickpeas and quinoa contribute protein and fiber. The recipe specifies cooked weights for both.' },
  'prep-oats-apple': { fresh: ['Milk', 'Apple'], staples: ['Oats', 'Almonds'], prep: 'Make three jars; keep nuts dry and slice fruit at serving.', finish: 'Add fruit and nuts when eating.', swaps: 'Use a labeled fortified soy drink for a dairy-free version. Nuts and dairy are allergens; choose suitable alternatives for your household.', nutrition: 'Oats supply fiber, milk supplies protein, and almonds add fat and texture. A milk alternative changes the totals.' },
};
export const prepSessions = [
  { id: 'a', title: 'Session A · Thai + Indian', recipes: ['prep-thai-basil-tofu', 'prep-indian-lentil-spinach'], shared: 'Carrot, cabbage, spinach, tomato, onion and garlic. Buy only the fresh quantities needed for these three days.', order: ['Wash and weigh the vegetables; set basil aside.', 'Start the dal first so it can simmer while you brown tofu.', 'Finish the tofu pan, portion both dishes and label the prep date.'] },
  { id: 'b', title: 'Session B · Nigerian + Vietnamese', recipes: ['prep-nigerian-beans', 'prep-vietnamese-tofu'], shared: 'Share tomatoes, onion and greens across both dishes. Recheck the fridge before buying the second small fresh-food shop.', order: ['Chop the shared tomato and onion batch, then divide it between the two recipes.', 'Simmer the beans sauce while the tofu browns in a second pan.', 'Finish both pots, portion promptly and keep garnishes separate.'] },
];
