import type {
  PantryItem,
  Recipe,
  Equipment,
  StoreDeal,
  UsageEvent,
} from "./types";
import { addDays, uid } from "./utils";

export const seedPantry: PantryItem[] = [
  {
    id: uid(),
    name: "Chicken breast",
    category: "Protein",
    quantity: 500,
    unit: "g",
    zone: "fridge",
    expiresOn: addDays(2),
    addedOn: addDays(-3),
  },
  {
    id: uid(),
    name: "Spaghetti",
    category: "Grains",
    quantity: 1,
    unit: "kg",
    zone: "pantry",
    expiresOn: addDays(180),
    addedOn: addDays(-30),
  },
  {
    id: uid(),
    name: "Canned tomatoes",
    category: "Pantry staple",
    quantity: 4,
    unit: "pcs",
    zone: "pantry",
    expiresOn: addDays(365),
    addedOn: addDays(-20),
  },
  {
    id: uid(),
    name: "Garlic",
    category: "Produce",
    quantity: 6,
    unit: "pcs",
    zone: "pantry",
    expiresOn: addDays(14),
    addedOn: addDays(-7),
  },
  {
    id: uid(),
    name: "Olive oil",
    category: "Oils",
    quantity: 500,
    unit: "ml",
    zone: "pantry",
    addedOn: addDays(-60),
  },
  {
    id: uid(),
    name: "Eggs",
    category: "Dairy",
    quantity: 8,
    unit: "pcs",
    zone: "fridge",
    expiresOn: addDays(10),
    addedOn: addDays(-2),
  },
  {
    id: uid(),
    name: "Spinach",
    category: "Produce",
    quantity: 200,
    unit: "g",
    zone: "fridge",
    expiresOn: addDays(1),
    addedOn: addDays(-4),
  },
  {
    id: uid(),
    name: "Parmesan",
    category: "Dairy",
    quantity: 150,
    unit: "g",
    zone: "fridge",
    expiresOn: addDays(45),
    addedOn: addDays(-10),
  },
  {
    id: uid(),
    name: "Frozen peas",
    category: "Frozen",
    quantity: 500,
    unit: "g",
    zone: "freezer",
    expiresOn: addDays(180),
    addedOn: addDays(-25),
  },
  {
    id: uid(),
    name: "Onion",
    category: "Produce",
    quantity: 3,
    unit: "pcs",
    zone: "pantry",
    expiresOn: addDays(20),
    addedOn: addDays(-5),
  },
  {
    id: uid(),
    name: "Rice",
    category: "Grains",
    quantity: 2,
    unit: "kg",
    zone: "pantry",
    addedOn: addDays(-90),
  },
  {
    id: uid(),
    name: "Soy sauce",
    category: "Condiments",
    quantity: 250,
    unit: "ml",
    zone: "pantry",
    addedOn: addDays(-120),
  },
];

export const seedRecipes: Recipe[] = [
  {
    id: "r-spaghetti-pomodoro",
    name: "Spaghetti Pomodoro",
    description: "Simple, garlicky tomato pasta — done in 20 minutes.",
    cuisine: "Italian",
    minutes: 20,
    difficulty: "easy",
    servings: 2,
    equipment: ["pot", "pan"],
    ingredients: [
      { name: "Spaghetti", quantity: 200, unit: "g" },
      { name: "Canned tomatoes", quantity: 1, unit: "pcs" },
      { name: "Garlic", quantity: 3, unit: "pcs" },
      { name: "Olive oil", quantity: 2, unit: "tbsp" },
      { name: "Parmesan", quantity: 30, unit: "g", optional: true },
    ],
    steps: [
      "Boil salted water and cook spaghetti to al dente.",
      "While pasta cooks, sauté sliced garlic in olive oil until fragrant.",
      "Add crushed tomatoes, season with salt and pepper, simmer 8 minutes.",
      "Toss drained pasta with sauce. Top with parmesan.",
    ],
    tags: ["quick", "vegetarian", "weeknight"],
  },
  {
    id: "r-garlic-chicken",
    name: "Pan-seared garlic chicken",
    description: "Crispy chicken breast with a buttery garlic finish.",
    cuisine: "American",
    minutes: 25,
    difficulty: "easy",
    servings: 2,
    equipment: ["pan"],
    ingredients: [
      { name: "Chicken breast", quantity: 400, unit: "g" },
      { name: "Garlic", quantity: 4, unit: "pcs" },
      { name: "Olive oil", quantity: 2, unit: "tbsp" },
    ],
    steps: [
      "Pat chicken dry, season with salt and pepper.",
      "Sear in hot pan with olive oil, 4 minutes per side.",
      "Add smashed garlic for the last 2 minutes.",
      "Rest 3 minutes, slice, and serve.",
    ],
    tags: ["high-protein", "quick", "weeknight"],
  },
  {
    id: "r-fried-rice",
    name: "Vegetable fried rice",
    description: "Use up leftover rice and any fridge odds-and-ends.",
    cuisine: "Asian",
    minutes: 15,
    difficulty: "easy",
    servings: 2,
    equipment: ["pan", "wok"],
    ingredients: [
      { name: "Rice", quantity: 300, unit: "g" },
      { name: "Eggs", quantity: 2, unit: "pcs" },
      { name: "Frozen peas", quantity: 100, unit: "g" },
      { name: "Soy sauce", quantity: 2, unit: "tbsp" },
      { name: "Garlic", quantity: 2, unit: "pcs" },
      { name: "Onion", quantity: 1, unit: "pcs" },
    ],
    steps: [
      "Heat oil in a wok over high heat. Scramble eggs and set aside.",
      "Sauté diced onion and garlic until soft.",
      "Add peas and rice, toss until heated through.",
      "Return eggs to wok, splash in soy sauce, finish with sesame oil if you have it.",
    ],
    tags: ["leftovers-friendly", "quick", "budget"],
  },
  {
    id: "r-creamy-spinach-eggs",
    name: "Creamy spinach eggs",
    description: "A skill-builder for one-pan brunch.",
    cuisine: "European",
    minutes: 12,
    difficulty: "easy",
    servings: 1,
    equipment: ["pan"],
    ingredients: [
      { name: "Eggs", quantity: 3, unit: "pcs" },
      { name: "Spinach", quantity: 100, unit: "g" },
      { name: "Parmesan", quantity: 20, unit: "g" },
      { name: "Garlic", quantity: 1, unit: "pcs" },
      { name: "Olive oil", quantity: 1, unit: "tbsp" },
    ],
    steps: [
      "Wilt spinach with garlic in olive oil.",
      "Push to the side, crack eggs into the pan.",
      "Cover, cook 3 minutes until whites set.",
      "Shower with parmesan and crack pepper.",
    ],
    tags: ["brunch", "vegetarian", "fast"],
  },
  {
    id: "r-roast-chicken-bowls",
    name: "Roast chicken rice bowls",
    description: "Meal-prep friendly bowls with grains, greens, and protein.",
    cuisine: "American",
    minutes: 40,
    difficulty: "medium",
    servings: 4,
    equipment: ["oven", "pan"],
    ingredients: [
      { name: "Chicken breast", quantity: 600, unit: "g" },
      { name: "Rice", quantity: 400, unit: "g" },
      { name: "Spinach", quantity: 200, unit: "g" },
      { name: "Soy sauce", quantity: 3, unit: "tbsp" },
      { name: "Garlic", quantity: 4, unit: "pcs" },
    ],
    steps: [
      "Marinate chicken in soy and crushed garlic 10 minutes.",
      "Roast at 200°C / 400°F for 22 minutes.",
      "Cook rice. Wilt spinach in the pan drippings.",
      "Slice chicken; build bowls. Add sriracha or peanut sauce to taste.",
    ],
    tags: ["meal-prep", "high-protein"],
  },
];

export const seedEquipment: Equipment[] = [
  { id: "eq-pan", name: "pan" },
  { id: "eq-pot", name: "pot" },
  { id: "eq-oven", name: "oven" },
  { id: "eq-wok", name: "wok" },
];

export const seedDeals: StoreDeal[] = [
  {
    id: uid(),
    store: "Trader Joe's",
    item: "Chicken breast",
    price: 4.99,
    unit: "lb",
    validUntil: addDays(5),
  },
  {
    id: uid(),
    store: "Whole Foods",
    item: "Olive oil",
    price: 8.99,
    unit: "500ml",
    validUntil: addDays(3),
  },
  {
    id: uid(),
    store: "Costco",
    item: "Eggs",
    price: 4.49,
    unit: "dozen",
    validUntil: addDays(7),
  },
  {
    id: uid(),
    store: "Safeway",
    item: "Spinach",
    price: 2.49,
    unit: "bag",
    validUntil: addDays(2),
  },
  {
    id: uid(),
    store: "Trader Joe's",
    item: "Frozen peas",
    price: 1.99,
    unit: "lb",
    validUntil: addDays(10),
  },
];

export const seedUsage: UsageEvent[] = [];
