import type {
  PantryItem,
  Recipe,
  Equipment,
  StoreDeal,
  UsageEvent,
} from "./types";
import { addDays, uid } from "./utils";

export const seedPantry: PantryItem[] = [
  {
    id: uid(),
    name: "Chicken breast",
    category: "Protein",
    quantity: 500,
    unit: "g",
    zone: "fridge",
    expiresOn: addDays(2),
    addedOn: addDays(-3),
  },
  {
    id: uid(),
    name: "Spaghetti",
    category: "Grains",
    quantity: 1,
    unit: "kg",
    zone: "pantry",
    expiresOn: addDays(180),
    addedOn: addDays(-30),
  },
  {
    id: uid(),
    name: "Canned tomatoes",
    category: "Pantry staple",
    quantity: 4,
    unit: "pcs",
    zone: "pantry",
    expiresOn: addDays(365),
    addedOn: addDays(-20),
  },
  {
    id: uid(),
    name: "Garlic",
    category: "Produce",
    quantity: 6,
    unit: "pcs",
    zone: "pantry",
    expiresOn: addDays(14),
    addedOn: addDays(-7),
  },
  {
    id: uid(),
    name: "Olive oil",
    category: "Oils",
    quantity: 500,
    unit: "ml",
    zone: "pantry",
    addedOn: addDays(-60),
  },
  {
    id: uid(),
    name: "Eggs",
    category: "Dairy",
    quantity: 8,
    unit: "pcs",
    zone: "fridge",
    expiresOn: addDays(10),
    addedOn: addDays(-2),
  },
  {
    id: uid(),
    name: "Spinach",
    category: "Produce",
    quantity: 200,
    unit: "g",
    zone: "fridge",
    expiresOn: addDays(1),
    addedOn: addDays(-4),
  },
  {
    id: uid(),
    name: "Parmesan",
    category: "Dairy",
    quantity: 150,
    unit: "g",
    zone: "fridge",
    expiresOn: addDays(45),
    addedOn: addDays(-10),
  },
  {
    id: uid(),
    name: "Frozen peas",
    category: "Frozen",
    quantity: 500,
    unit: "g",
    zone: "freezer",
    expiresOn: addDays(180),
    addedOn: addDays(-25),
  },
  {
    id: uid(),
    name: "Onion",
    category: "Produce",
    quantity: 3,
    unit: "pcs",
    zone: "pantry",
    expiresOn: addDays(20),
    addedOn: addDays(-5),
  },
  {
    id: uid(),
    name: "Rice",
    category: "Grains",
    quantity: 2,
    unit: "kg",
    zone: "pantry",
    addedOn: addDays(-90),
  },
  {
    id: uid(),
    name: "Soy sauce",
    category: "Condiments",
    quantity: 250,
    unit: "ml",
    zone: "pantry",
    addedOn: addDays(-120),
  },
];

// Chef Pham's Recipes 👩🏻‍🍳 — a real, curated collection across Thai, Vietnamese,
// Chinese, Korean, Nigerian, Indian and American cooking, with a vegan/vegetarian
// lean. Quantities are sensible approximations where the source was qualitative.
// Pantry staples used throughout:
//   FS = vegetarian (pineapple) fish sauce · MS = mushroom seasoning
//   (both made in Vietnam, available at Hong Kong 4 supermarket).
export const seedRecipes: Recipe[] = [
  // ───────────────────────── THAI ─────────────────────────
  {
    id: "r-basil-thai-spaghetti",
    name: "Basil Thai Spaghetti",
    description:
      "Holy-basil stir-fried spaghetti with fried tofu and four-colour bell peppers.",
    cuisine: "Thai",
    minutes: 35,
    difficulty: "easy",
    servings: 4,
    equipment: ["pot", "wok"],
    ingredients: [
      { name: "Thai basil leaves", quantity: 2, unit: "cup" },
      { name: "Roma tomatoes", quantity: 4, unit: "pcs" },
      { name: "Fried tofu", quantity: 250, unit: "g" },
      { name: "Bell peppers", quantity: 4, unit: "pcs" },
      { name: "Spaghetti", quantity: 300, unit: "g" },
      { name: "Vegetarian Worcestershire sauce", quantity: 2, unit: "tbsp" },
      { name: "Mushroom seasoning", quantity: 1, unit: "tsp" },
    ],
    steps: [
      "Boil the spaghetti to al dente, drain, and set aside.",
      "In a hot wok with oil, stir-fry the sliced bell peppers and fried tofu until charred at the edges.",
      "Add the chopped tomatoes and cook until they break down.",
      "Season with vegetarian Worcestershire sauce and mushroom seasoning.",
      "Toss in the drained spaghetti and a big handful of Thai basil; stir until the basil wilts.",
    ],
    tags: ["thai", "vegan", "vegetarian", "noodles"],
  },
  {
    id: "r-thai-raw-papaya-salad",
    name: "Thai Raw Papaya Salad",
    description: "Som tum — shredded green papaya, sharp lime, tamarind and palm sugar.",
    cuisine: "Thai",
    minutes: 25,
    difficulty: "easy",
    servings: 2,
    equipment: [],
    ingredients: [
      { name: "Green papaya", quantity: 1, unit: "pcs" },
      { name: "Garlic", quantity: 2, unit: "pcs" },
      { name: "Grape tomatoes", quantity: 8, unit: "pcs" },
      { name: "Green beans", quantity: 15, unit: "pcs" },
      { name: "Palm sugar", quantity: 1, unit: "tbsp" },
      { name: "Lime juice", quantity: 2, unit: "tbsp" },
      { name: "Tamarind juice", quantity: 1, unit: "tbsp" },
      { name: "Vegetarian fish sauce", quantity: 1, unit: "tbsp" },
      { name: "Thai chilies", quantity: 2, unit: "pcs", optional: true },
      { name: "Roasted peanuts", quantity: 3, unit: "tbsp", optional: true },
    ],
    steps: [
      "Peel and shred the green papaya into long thin strands.",
      "Pound the garlic (and chilies, if using) into a rough paste.",
      "Add the halved green beans and grape tomatoes; bruise lightly.",
      "Dress with palm sugar, lime juice, tamarind juice and vegetarian fish sauce; toss well.",
      "Taste and adjust, then top with coarsely crushed roasted peanuts.",
    ],
    tags: ["thai", "vegan", "vegetarian", "salad", "no-cook"],
  },
  {
    id: "r-thai-eggs",
    name: "Thai Crispy Eggs",
    description: "Fluffy, golden wok-fried eggs with lime and crispy garlic.",
    cuisine: "Thai",
    minutes: 15,
    difficulty: "easy",
    servings: 2,
    equipment: ["wok"],
    ingredients: [
      { name: "Eggs", quantity: 2, unit: "pcs" },
      { name: "Green onions", quantity: 2, unit: "pcs" },
      { name: "Lime juice", quantity: 1, unit: "tsp" },
      { name: "Cornstarch", quantity: 1, unit: "tbsp" },
      { name: "Water", quantity: 1, unit: "tbsp" },
      { name: "Vegetarian fish sauce", quantity: 1, unit: "tsp" },
      { name: "Thai chilies", quantity: 2, unit: "pcs", optional: true },
      { name: "Crispy garlic", quantity: 1, unit: "tbsp", optional: true },
      { name: "White rice", quantity: 1, unit: "cup", optional: true },
    ],
    steps: [
      "Whisk the eggs with lime juice, vegetarian fish sauce, water, cornstarch and sliced green onions.",
      "Heat a wok with plenty of oil on high until shimmering.",
      "Pour in a little of the mixture at a time — it puffs up fast; let it go ~30 seconds, then flip.",
      "Cook until golden and crispy, then drain on paper towels.",
      "Top with green onions, Thai chilies and crispy garlic. Serve with white rice.",
    ],
    tags: ["thai", "vegetarian", "quick", "eggs"],
  },
  {
    id: "r-mango-bango",
    name: "Mango Bango",
    description: "Chilled mango, sago and coconut jelly in sweet creamy milk.",
    cuisine: "Thai",
    minutes: 20,
    difficulty: "easy",
    servings: 4,
    equipment: ["pot"],
    ingredients: [
      { name: "Sago pearls", quantity: 0.5, unit: "cup" },
      { name: "Nata de coco", quantity: 1, unit: "cup" },
      { name: "Champagne mangoes", quantity: 3, unit: "pcs" },
      { name: "Half and half", quantity: 1.5, unit: "cup" },
      { name: "Condensed milk", quantity: 0.5, unit: "cup" },
    ],
    steps: [
      "Boil the sago for 10 minutes, then cover off the heat for 15 minutes.",
      "Drain and rinse the sago under cold water.",
      "Cube the mangoes.",
      "Combine mango, sago, drained nata de coco, half and half and condensed milk in a bowl.",
      "Refrigerate at least 4 hours before serving.",
    ],
    tags: ["thai", "vegetarian", "dessert", "make-ahead"],
  },

  // ────────────────────── VIETNAMESE ──────────────────────
  {
    id: "r-malabar-spinach-soup",
    name: "Malabar Spinach Soup",
    description: "A clean, fast Vietnamese green soup — barely any effort.",
    cuisine: "Vietnamese",
    minutes: 15,
    difficulty: "easy",
    servings: 2,
    equipment: ["pot"],
    ingredients: [
      { name: "Malabar spinach", quantity: 300, unit: "g" },
      { name: "Mushroom seasoning", quantity: 1, unit: "tsp" },
      { name: "Vegetarian fish sauce", quantity: 1, unit: "tsp" },
    ],
    steps: [
      "Wash the Malabar spinach thoroughly and let it dry as much as possible.",
      "Bring a pot of water to a boil.",
      "Line up the spinach and chop into ½-inch lengths.",
      "Add to the boiling water with mushroom seasoning and vegetarian fish sauce.",
      "Boil 7–10 minutes — no longer, or the leaves turn mushy. Taste and adjust.",
    ],
    tags: ["vietnamese", "vegan", "vegetarian", "soup", "quick"],
  },
  {
    id: "r-viet-udon-mushrooms",
    name: "Vietnamese Udon Noodles with Mushrooms",
    description: "Four kinds of mushroom, charred and glazed, tossed with chewy udon.",
    cuisine: "Vietnamese",
    minutes: 30,
    difficulty: "medium",
    servings: 2,
    equipment: ["wok", "pot"],
    ingredients: [
      { name: "Wood ear mushrooms", quantity: 50, unit: "g" },
      { name: "Seafood mushrooms", quantity: 100, unit: "g" },
      { name: "Enoki mushrooms", quantity: 100, unit: "g" },
      { name: "Shiitake mushrooms", quantity: 100, unit: "g" },
      { name: "Udon noodles", quantity: 400, unit: "g" },
      { name: "Vegetable broth", quantity: 2, unit: "cup" },
      { name: "Garlic powder", quantity: 1, unit: "tsp" },
      { name: "Onion powder", quantity: 1, unit: "tsp" },
      { name: "Soy sauce", quantity: 2, unit: "tbsp" },
      { name: "Mushroom seasoning", quantity: 1, unit: "tsp" },
      { name: "Vegetarian fish sauce", quantity: 1, unit: "tsp" },
      { name: "Chili oil", quantity: 1, unit: "tbsp", optional: true },
    ],
    steps: [
      "Cut all the mushrooms and stir-fry them hard — the more charred, the better.",
      "Add the vegetable broth and let the mushrooms soak it up; reduce until almost dry.",
      "Meanwhile, boil the udon noodles and strain.",
      "Add oil to a pan, then the noodles and mushrooms (ideally with no broth left over).",
      "Add all the seasonings and stir-fry together. Finish with chili oil if you like heat.",
    ],
    tags: ["vietnamese", "vegan", "vegetarian", "noodles", "mushroom"],
  },
  {
    id: "r-spicy-bamboo-shoot",
    name: "Spicy Bamboo Shoots",
    description: "Quick braised bamboo shoots and mushroom in a sweet-spicy glaze.",
    cuisine: "Vietnamese",
    minutes: 15,
    difficulty: "easy",
    servings: 2,
    equipment: ["pan"],
    ingredients: [
      { name: "Bamboo shoots", quantity: 200, unit: "g" },
      { name: "Mushrooms", quantity: 100, unit: "g" },
      { name: "Chili", quantity: 2, unit: "pcs" },
      { name: "Soy sauce", quantity: 1, unit: "tbsp" },
      { name: "Sugar", quantity: 1, unit: "tsp" },
      { name: "Chili sauce", quantity: 1, unit: "tbsp" },
      { name: "Water", quantity: 2, unit: "tbsp" },
    ],
    steps: [
      "Slice the bamboo shoots and mushrooms.",
      "Simmer everything together with the chili, soy sauce, sugar, chili sauce and water.",
      "Cook down until the sauce clings and almost no liquid is left.",
    ],
    tags: ["vietnamese", "vegan", "vegetarian", "spicy", "quick"],
  },

  // ─────────────────────── CHINESE ────────────────────────
  {
    id: "r-chinese-egg-noodles",
    name: "Stir-fried Chinese Egg Noodles",
    description: "Loaded noodles with mushrooms, tofu, fish balls and Chinese sausage.",
    cuisine: "Chinese",
    minutes: 30,
    difficulty: "medium",
    servings: 3,
    equipment: ["wok"],
    ingredients: [
      { name: "Egg noodles", quantity: 300, unit: "g" },
      { name: "Seafood mushrooms", quantity: 100, unit: "g" },
      { name: "King oyster mushrooms", quantity: 100, unit: "g" },
      { name: "Wood ear mushrooms", quantity: 50, unit: "g" },
      { name: "Shiitake mushrooms", quantity: 100, unit: "g" },
      { name: "Bean sprouts", quantity: 150, unit: "g" },
      { name: "Gai lan", quantity: 200, unit: "g" },
      { name: "Eggs", quantity: 3, unit: "pcs" },
      { name: "Firm tofu", quantity: 200, unit: "g" },
      { name: "Fried fish balls", quantity: 150, unit: "g" },
      { name: "Chinese sausage", quantity: 100, unit: "g" },
      { name: "Oyster sauce", quantity: 2, unit: "tbsp" },
      { name: "Soy sauce", quantity: 2, unit: "tbsp" },
      { name: "Mushroom seasoning", quantity: 1, unit: "tsp" },
      { name: "Vegetarian fish sauce", quantity: 1, unit: "tsp" },
    ],
    steps: [
      "Blanch or soften the egg noodles and set aside.",
      "Stir-fry the sliced Chinese sausage and fish balls until they render and brown.",
      "Add all the mushrooms and the tofu; cook until charred at the edges.",
      "Push aside and scramble the eggs in the wok.",
      "Add the gai lan and bean sprouts, then the noodles, oyster sauce, soy sauce, MS and FS; toss until glossy.",
    ],
    tags: ["chinese", "noodles", "stir-fry"],
  },
  {
    id: "r-garlic-eggplant-tofu",
    name: "Garlic Eggplant and Crispy Tofu",
    description: "Silky eggplant and golden tofu cubes in a glossy garlic-ginger sauce.",
    cuisine: "Chinese",
    minutes: 30,
    difficulty: "medium",
    servings: 2,
    equipment: ["wok"],
    ingredients: [
      { name: "Chinese eggplants", quantity: 2, unit: "pcs" },
      { name: "Extra-firm tofu", quantity: 400, unit: "g" },
      { name: "Green onions", quantity: 3, unit: "pcs" },
      { name: "Garlic", quantity: 1, unit: "tbsp" },
      { name: "Cornstarch", quantity: 0.25, unit: "cup" },
      { name: "Vegetable oil", quantity: 3, unit: "tbsp" },
      { name: "Soy sauce", quantity: 2, unit: "tbsp" },
      { name: "Oyster sauce", quantity: 2, unit: "tbsp" },
      { name: "Dark soy sauce", quantity: 1, unit: "tbsp" },
      { name: "Black vinegar", quantity: 0.5, unit: "tbsp" },
      { name: "Ginger paste", quantity: 0.5, unit: "tbsp" },
      { name: "Brown sugar", quantity: 1, unit: "tbsp" },
      { name: "Sesame seeds", quantity: 1, unit: "tbsp", optional: true },
    ],
    steps: [
      "Press the tofu to remove moisture, cut into ¾-inch cubes, and dust with cornstarch.",
      "Quarter the eggplants lengthwise, cut into ½-inch chunks, and dust with cornstarch.",
      "Whisk the sauce: soy, oyster, dark soy, black vinegar, ginger paste and brown sugar.",
      "Fry the eggplant in oil over medium-high until crispy in spots and soft through, 5–7 minutes; remove.",
      "Fry the tofu in fresh oil until golden on most sides, ~10 minutes; remove.",
      "Sauté the garlic and green onion whites 1 minute, add the sauce, then return tofu and eggplant and toss.",
      "Top with onion greens and sesame seeds; serve with white rice.",
    ],
    tags: ["chinese", "vegetarian", "tofu", "rice"],
  },

  // ──────────────────────── KOREAN ────────────────────────
  {
    id: "r-kimbap-bowl",
    name: "Kimbap Bowl",
    description: "Deconstructed kimbap — seasoned veg and tofu over rice with a gochujang drizzle.",
    cuisine: "Korean",
    minutes: 30,
    difficulty: "easy",
    servings: 2,
    equipment: ["pan", "pot"],
    ingredients: [
      { name: "White rice", quantity: 1.5, unit: "cup" },
      { name: "Spinach", quantity: 150, unit: "g" },
      { name: "Carrots", quantity: 2, unit: "pcs" },
      { name: "Tofu", quantity: 200, unit: "g" },
      { name: "Mushrooms", quantity: 150, unit: "g" },
      { name: "Eggs", quantity: 2, unit: "pcs" },
      { name: "Gochujang", quantity: 2, unit: "tbsp" },
      { name: "Sesame oil", quantity: 1, unit: "tbsp" },
      { name: "Soy sauce", quantity: 1, unit: "tbsp" },
      { name: "Garlic", quantity: 2, unit: "pcs" },
      { name: "Sesame seeds", quantity: 1, unit: "tbsp" },
    ],
    steps: [
      "Cook the white rice.",
      "Steam the spinach; grate and sauté the carrots; sauté the mushrooms.",
      "Pan-fry the soy-marinated tofu until golden.",
      "Fry the eggs sunny-side up.",
      "Mix the sauce: gochujang, sesame oil, soy sauce, minced garlic and sesame seeds.",
      "Arrange everything over rice, top with an egg, and drizzle the red sauce.",
    ],
    tags: ["korean", "vegetarian", "bowl", "rice"],
  },

  // ─────────────────────── NIGERIAN ───────────────────────
  {
    id: "r-nigerian-jollof",
    name: "Nigerian Jollof Rice",
    description:
      "Olaiya's smoky party jollof — long-fried pepper base, deeply seasoned. (Vegetarian; add chicken stock if you like.)",
    cuisine: "Nigerian",
    minutes: 100,
    difficulty: "medium",
    servings: 6,
    equipment: ["pot"],
    ingredients: [
      { name: "Tomatoes", quantity: 6, unit: "pcs" },
      { name: "Red bell pepper", quantity: 2, unit: "pcs" },
      { name: "Habanero", quantity: 2, unit: "pcs" },
      { name: "Onion", quantity: 2, unit: "pcs" },
      { name: "Tomato paste", quantity: 3, unit: "tbsp" },
      { name: "Vegetable oil", quantity: 4, unit: "tbsp" },
      { name: "Parboiled rice", quantity: 3, unit: "cup" },
      { name: "Vegetable stock", quantity: 3, unit: "cup" },
      { name: "Bouillon cube", quantity: 1, unit: "pcs" },
      { name: "Jollof seasoning", quantity: 1, unit: "tsp" },
      { name: "Curry powder", quantity: 0.5, unit: "tsp" },
      { name: "Thyme", quantity: 0.5, unit: "tsp" },
      { name: "Salt", quantity: 1, unit: "tsp" },
      { name: "Bay leaves", quantity: 2, unit: "pcs" },
    ],
    steps: [
      "Blend the tomatoes, red bell pepper, habanero and a little onion (a little green pepper too, if you like).",
      "Heat oil over medium-high, brown the remaining onions, then add the tomato paste.",
      "Add the blended tomatoes and fry the whole mixture, stirring constantly, for about 30 minutes.",
      "Lower to medium and add the stock, salt, curry, thyme, jollof seasoning and the bouillon cube; boil 10 minutes.",
      "Add the parboiled rice and bay leaves, topping up with water as needed; cook on medium-low 15–30 minutes.",
      "When the rice has absorbed most of the stew, stir in any reserved blended tomatoes.",
      "Cover 5–10 minutes and mix until dry and fluffy.",
    ],
    tags: ["nigerian", "vegan", "vegetarian", "rice", "party"],
  },

  // ──────────────────────── INDIAN ────────────────────────
  {
    id: "r-paneer",
    name: "Homemade Paneer",
    description: "Fresh pressed paneer from scratch — just milk and vinegar.",
    cuisine: "Indian",
    minutes: 60,
    difficulty: "medium",
    servings: 4,
    equipment: ["pot"],
    ingredients: [
      { name: "Whole milk", quantity: 4, unit: "l" },
      { name: "Vinegar", quantity: 12, unit: "tbsp" },
    ],
    steps: [
      "Bring the milk to a boil, then remove from the heat the moment it boils.",
      "Slowly drizzle in the vinegar while stirring; the milk curdles immediately. Let stand 10 minutes.",
      "Pour into a cheesecloth-lined strainer; rinse the curds under cold water, working out the vinegar gently.",
      "Gather the cheesecloth and squeeze out the remaining liquid.",
      "Fold flat on a plate, stack plates on top to press, and refrigerate ~2 hours to firm up.",
    ],
    tags: ["indian", "vegetarian", "cheese", "make-ahead"],
  },
  {
    id: "r-fluffy-basmati-rice",
    name: "Fluffy Basmati Rice (Auntie's Method)",
    description: "Spiced, separate-grain basmati using the drain-and-steam trick.",
    cuisine: "Indian",
    minutes: 40,
    difficulty: "easy",
    servings: 4,
    equipment: ["pot"],
    ingredients: [
      { name: "Sella basmati rice", quantity: 2, unit: "cup" },
      { name: "Ghee", quantity: 2, unit: "tbsp" },
      { name: "Whole garam masala spices", quantity: 1, unit: "tbsp" },
      { name: "Salt", quantity: 1, unit: "tsp" },
      { name: "Water", quantity: 8, unit: "cup" },
    ],
    steps: [
      "Soak the basmati rice for 30 minutes.",
      "Bloom the whole garam masala spices in ghee for a minute.",
      "Add salt and lots of water and cook until the rice is soft.",
      "Strain off ALL the water, return the rice to the pot on the lowest heat, and cover tightly.",
      "Trap the heat for ~2 minutes to steam, then fluff.",
    ],
    tags: ["indian", "vegetarian", "rice", "side"],
  },

  // ─────────────────────── AMERICAN ───────────────────────
  {
    id: "r-jennifer-grilled-cheese",
    name: "Jennifer's Famous Grilled Cheese",
    description: "A five-cheese melt griddled in sea-salt butter.",
    cuisine: "American",
    minutes: 5,
    difficulty: "easy",
    servings: 1,
    equipment: ["pan"],
    ingredients: [
      { name: "Bread", quantity: 2, unit: "pcs" },
      { name: "Butter", quantity: 1, unit: "tbsp" },
      { name: "Smoked gouda", quantity: 30, unit: "g" },
      { name: "Swiss cheese", quantity: 30, unit: "g" },
      { name: "American cheese", quantity: 1, unit: "pcs" },
      { name: "Oaxaca cheese", quantity: 30, unit: "g" },
      { name: "Mozzarella", quantity: 30, unit: "g" },
    ],
    steps: [
      "Butter the outsides of the bread with olive-oil sea-salt butter.",
      "Layer all five cheeses between the slices.",
      "Griddle low and slow until deep golden and fully melted, flipping once.",
    ],
    tags: ["american", "vegetarian", "quick", "comfort"],
  },
  {
    id: "r-quinoa-salad",
    name: "Costco-Style Quinoa Salad",
    description: "A big batch grain-and-veg salad that keeps all week.",
    cuisine: "American",
    minutes: 5,
    difficulty: "easy",
    servings: 4,
    equipment: [],
    ingredients: [
      { name: "Cooked quinoa", quantity: 1, unit: "cup" },
      { name: "Cooked brown rice", quantity: 0.5, unit: "cup" },
      { name: "Cucumber", quantity: 1, unit: "pcs" },
      { name: "Tomatoes", quantity: 2, unit: "pcs" },
      { name: "Red bell peppers", quantity: 1, unit: "pcs" },
      { name: "Mung beans", quantity: 0.5, unit: "cup" },
      { name: "Red lentils", quantity: 0.5, unit: "cup" },
      { name: "Kale", quantity: 100, unit: "g" },
      { name: "Cauliflower", quantity: 150, unit: "g" },
      { name: "Lemon vinaigrette", quantity: 3, unit: "tbsp" },
    ],
    steps: [
      "Chop the cucumber, tomatoes, peppers, kale and cauliflower small.",
      "Combine with the cooked quinoa, brown rice, mung beans and lentils.",
      "Toss with the lemon vinaigrette; chill before serving.",
    ],
    tags: ["american", "vegan", "vegetarian", "salad", "meal-prep", "no-cook"],
  },
  {
    id: "r-butter-garlic-pasta",
    name: "Butter Garlic Pasta",
    description: "Glossy garlic-butter pasta with parmesan and chili flakes.",
    cuisine: "American",
    minutes: 20,
    difficulty: "easy",
    servings: 2,
    equipment: ["pot", "pan"],
    ingredients: [
      { name: "Pasta", quantity: 225, unit: "g" },
      { name: "Butter", quantity: 3, unit: "tbsp" },
      { name: "Onion", quantity: 0.5, unit: "pcs" },
      { name: "Garlic", quantity: 5, unit: "pcs" },
      { name: "Parmesan", quantity: 0.5, unit: "cup" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
      { name: "Black pepper", quantity: 1, unit: "tsp" },
      { name: "Chili flakes", quantity: 0.5, unit: "tsp" },
      { name: "Oregano", quantity: 1, unit: "tsp" },
      { name: "Basil", quantity: 1, unit: "tsp", optional: true },
    ],
    steps: [
      "Cook the pasta, reserving ¼ cup of pasta water before draining.",
      "Melt the butter and soften the finely chopped onion and minced garlic.",
      "Stir in salt, pepper, chili flakes, oregano and basil.",
      "Toss the pasta with the grated parmesan and pasta water until creamy.",
    ],
    tags: ["american", "vegetarian", "pasta", "quick"],
  },
  {
    id: "r-yoyos-veggie-hotdog",
    name: "Yoyos Veggie Hotdog",
    description: "Loaded soy dog with caramelized onions, sriracha, cream cheese and honey mayo.",
    cuisine: "American",
    minutes: 10,
    difficulty: "easy",
    servings: 1,
    equipment: ["pan"],
    ingredients: [
      { name: "Soy hotdog", quantity: 1, unit: "pcs" },
      { name: "Hotdog bun", quantity: 1, unit: "pcs" },
      { name: "Caramelized onions", quantity: 2, unit: "tbsp" },
      { name: "Crispy fried onions", quantity: 1, unit: "tbsp" },
      { name: "Sriracha", quantity: 1, unit: "tbsp" },
      { name: "Cream cheese", quantity: 1, unit: "tbsp" },
      { name: "Honey mayo", quantity: 1, unit: "tbsp" },
    ],
    steps: [
      "Pan-fry the soy hotdog until browned.",
      "Tuck it into the bun with the caramelized onions.",
      "Top with crispy fried onions, sriracha, cream cheese and honey mayo.",
    ],
    tags: ["american", "vegetarian", "quick", "street-food"],
  },

  // ─────────────────────── BREAKFAST ──────────────────────
  {
    id: "r-breakfast-potatoes",
    name: "Best Breakfast Potatoes",
    description: "Crispy diced potatoes with a steak-seasoning and jollof-spice crust.",
    cuisine: "American",
    minutes: 20,
    difficulty: "easy",
    servings: 2,
    equipment: ["pan"],
    ingredients: [
      { name: "Potatoes", quantity: 3, unit: "pcs" },
      { name: "Montreal steak seasoning", quantity: 1, unit: "tbsp" },
      { name: "Jollof seasoning", quantity: 1, unit: "tsp" },
      { name: "Garlic powder", quantity: 1, unit: "tsp" },
      { name: "Onion powder", quantity: 1, unit: "tsp" },
      { name: "Black pepper", quantity: 0.5, unit: "tsp" },
      { name: "Vegetable oil", quantity: 2, unit: "tbsp" },
    ],
    steps: [
      "Dice the potatoes into big chunks.",
      "Toss with the seasonings and oil.",
      "Fry, undisturbed at first, until browned completely and crispy on all sides.",
    ],
    tags: ["breakfast", "vegan", "vegetarian", "quick", "potato"],
  },

  // ───────────────────────── SAUCES ───────────────────────
  {
    id: "r-chimichurri",
    name: "The Crack Sauce (Chimichurri)",
    description: "Bright herb-and-garlic sauce that keeps over two weeks — good on everything.",
    cuisine: "Latin American",
    minutes: 15,
    difficulty: "easy",
    servings: 8,
    equipment: [],
    ingredients: [
      { name: "Parsley", quantity: 0.25, unit: "cup" },
      { name: "Cilantro", quantity: 1, unit: "tbsp" },
      { name: "Red onion", quantity: 2, unit: "tbsp" },
      { name: "Garlic", quantity: 4, unit: "pcs" },
      { name: "Dried oregano", quantity: 0.5, unit: "tbsp" },
      { name: "Chili flakes", quantity: 1, unit: "tsp" },
      { name: "Black pepper", quantity: 0.5, unit: "tsp" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
      { name: "Olive oil", quantity: 0.25, unit: "cup" },
      { name: "Red wine vinegar", quantity: 1.5, unit: "tbsp" },
      { name: "Lemon juice", quantity: 1, unit: "tsp" },
    ],
    steps: [
      "Finely chop the parsley, cilantro, red onion and garlic.",
      "Combine with the oregano, chili flakes, pepper, salt, olive oil, red wine vinegar and lemon juice.",
      "Mix well, taste and adjust, and rest 15–20 minutes before serving.",
      "Store in an airtight container in the fridge — keeps over 2 weeks.",
    ],
    tags: ["sauce", "vegan", "vegetarian", "no-cook", "condiment"],
  },

  // ──────────────────────── DESSERTS ──────────────────────
  {
    id: "r-oreo-milk-bread",
    name: "Oreo Milk Bread",
    description: "Brioche soaked in Oreo milk, pan-fried golden, and topped with ice cream.",
    cuisine: "American",
    minutes: 15,
    difficulty: "easy",
    servings: 4,
    equipment: ["pan"],
    ingredients: [
      { name: "Brioche bread", quantity: 8, unit: "pcs" },
      { name: "Oreos", quantity: 10, unit: "pcs" },
      { name: "Whole milk", quantity: 2, unit: "cup" },
      { name: "Butter", quantity: 2, unit: "tbsp" },
      { name: "Oreo ice cream", quantity: 2, unit: "pcs", optional: true },
      { name: "Condensed milk", quantity: 1, unit: "cup", optional: true },
    ],
    steps: [
      "Blitz the Oreos to a fine powder, then stir into the milk — don't over-mix (avoid grey milk).",
      "Slice the brioche into 2-inch pieces and soak in the Oreo milk until it drinks it up.",
      "Melt the butter in a skillet and fry the soaked bread ~3 minutes per side until golden.",
      "Top with a scoop of Oreo ice cream and a drizzle of condensed milk.",
    ],
    tags: ["dessert", "vegetarian", "sweet"],
  },
];

export const seedEquipment: Equipment[] = [
  { id: "eq-pan", name: "pan" },
  { id: "eq-pot", name: "pot" },
  { id: "eq-oven", name: "oven" },
  { id: "eq-wok", name: "wok" },
];

export const seedDeals: StoreDeal[] = [
  {
    id: uid(),
    store: "Trader Joe's",
    item: "Chicken breast",
    price: 4.99,
    unit: "lb",
    validUntil: addDays(5),
  },
  {
    id: uid(),
    store: "Whole Foods",
    item: "Olive oil",
    price: 8.99,
    unit: "500ml",
    validUntil: addDays(3),
  },
  {
    id: uid(),
    store: "Costco",
    item: "Eggs",
    price: 4.49,
    unit: "dozen",
    validUntil: addDays(7),
  },
  {
    id: uid(),
    store: "Safeway",
    item: "Spinach",
    price: 2.49,
    unit: "bag",
    validUntil: addDays(2),
  },
  {
    id: uid(),
    store: "Trader Joe's",
    item: "Frozen peas",
    price: 1.99,
    unit: "lb",
    validUntil: addDays(10),
  },
];

export const seedUsage: UsageEvent[] = [];
