-- ============================================================================
-- Expand the food consortium: more canonical ingredients, and turn the cooking
-- techniques into real guides (with markdown body content). Additive + idempotent.
-- Nutrition per 100 g, USDA (public domain).
-- ============================================================================

insert into public.ingredients
  (slug, name, category, aliases, grams_per_piece, calories, protein_g, carbs_g, fat_g, fiber_g)
values
  ('cucumber','Cucumber','Produce','{cucumbers}',300,15,0.7,3.6,0.1,0.5),
  ('broccoli','Broccoli','Produce','{}',null,34,2.8,7,0.4,2.6),
  ('cauliflower','Cauliflower','Produce','{}',null,25,1.9,5,0.3,2),
  ('zucchini','Zucchini','Produce','{courgette}',196,17,1.2,3.1,0.3,1),
  ('mushroom','Mushroom','Produce','{mushrooms}',null,22,3.1,3.3,0.3,1),
  ('avocado','Avocado','Produce','{avocados}',200,160,2,9,15,7),
  ('apple','Apple','Produce','{apples}',182,52,0.3,14,0.2,2.4),
  ('orange','Orange','Produce','{oranges}',131,47,0.9,12,0.1,2.4),
  ('strawberry','Strawberry','Produce','{strawberries}',null,32,0.7,7.7,0.3,2),
  ('blueberry','Blueberry','Produce','{blueberries}',null,57,0.7,14,0.3,2.4),
  ('ginger','Ginger','Produce','{}',null,80,1.8,18,0.8,2),
  ('cilantro','Cilantro','Produce','{coriander}',null,23,2.1,3.7,0.5,2.8),
  ('kale','Kale','Produce','{}',null,49,4.3,9,0.9,3.6),
  ('sweet-potato','Sweet potato','Produce','{sweet potatoes,yam}',130,86,1.6,20,0.1,3),
  ('pork','Pork','Meat & Seafood','{pork chop}',null,242,27,0,14,0),
  ('turkey','Turkey','Meat & Seafood','{}',null,135,29,0,1,0),
  ('tuna','Tuna','Meat & Seafood','{}',null,132,28,0,1,0),
  ('cod','Cod','Meat & Seafood','{}',null,82,18,0,0.7,0),
  ('tofu','Tofu','Legumes & Nuts','{bean curd}',null,76,8,1.9,4.8,0.3),
  ('oats','Oats','Grains & Bread','{oatmeal,rolled oats}',null,389,17,66,7,11),
  ('quinoa','Quinoa','Grains & Bread','{}',null,120,4.4,21,1.9,2.8),
  ('couscous','Couscous','Grains & Bread','{}',null,112,3.8,23,0.2,1.4),
  ('tortilla','Tortilla','Grains & Bread','{tortillas}',null,310,8,52,7,3),
  ('mozzarella','Mozzarella','Dairy & Eggs','{}',null,280,28,3.1,17,0),
  ('parmesan','Parmesan','Dairy & Eggs','{parmigiano}',null,392,36,3.2,29,0),
  ('kidney-beans','Kidney beans','Legumes & Nuts','{}',null,127,8.7,23,0.5,6.4),
  ('walnuts','Walnuts','Legumes & Nuts','{}',null,654,15,14,65,6.7),
  ('cashews','Cashews','Legumes & Nuts','{}',null,553,18,30,44,3.3),
  ('black-pepper','Black pepper','Pantry & Spices','{pepper}',null,251,10,64,3.3,25),
  ('cumin','Cumin','Pantry & Spices','{}',null,375,18,44,22,11),
  ('paprika','Paprika','Pantry & Spices','{}',null,282,14,54,13,35),
  ('cinnamon','Cinnamon','Pantry & Spices','{}',null,247,4,81,1.2,53),
  ('chili-powder','Chili powder','Pantry & Spices','{}',null,282,13,50,14,35),
  ('cocoa-powder','Cocoa powder','Pantry & Spices','{cocoa}',null,228,20,58,14,37),
  ('vanilla-extract','Vanilla extract','Pantry & Spices','{vanilla}',null,288,0.1,13,0.1,0),
  ('vegetable-oil','Vegetable oil','Oils & Condiments','{canola oil}',null,884,0,0,100,0),
  ('sesame-oil','Sesame oil','Oils & Condiments','{}',null,884,0,0,100,0),
  ('vinegar','Vinegar','Oils & Condiments','{}',null,18,0,0.9,0,0),
  ('ketchup','Ketchup','Oils & Condiments','{}',null,101,1,27,0.1,0.3),
  ('mustard','Mustard','Oils & Condiments','{}',null,66,4,5,4,3),
  ('mayonnaise','Mayonnaise','Oils & Condiments','{mayo}',null,680,1,0.6,75,0),
  ('coconut-milk','Coconut milk','Dairy & Eggs','{}',null,230,2.3,6,24,2.2)
on conflict (slug) do nothing;

-- Techniques become real guides: enrich the original five with body content and
-- add ten more. Upsert so existing rows gain their bodies.
insert into public.techniques (slug, title, category, difficulty, minutes, summary, body, tags)
values
  ('blanching','Blanching','Vegetables','easy',10,
   'Briefly boil vegetables, then plunge into ice water to set colour and stop cooking.',
   E'1. Bring a large pot of salted water to a rolling boil and prepare a bowl of ice water.\n2. Drop in the vegetables and cook 30 seconds to 3 minutes depending on size.\n3. Lift them straight into the ice bath to halt cooking and lock in colour.\n4. Drain well. Great for prepping greens, beans, and tomatoes (the skins slip off).',
   '{vegetables,prep,boil}'),
  ('searing','Searing','Heat & Protein','medium',15,
   'Brown protein in a very hot pan to build deep flavour via the Maillard reaction.',
   E'1. Pat the protein bone-dry and season.\n2. Heat a heavy pan until just smoking, add a thin film of high-smoke-point oil.\n3. Lay the food away from you and **do not move it** for 2-4 minutes — it releases when a crust forms.\n4. Flip once, finish, then rest. A fond (browned bits) is left behind for a pan sauce.',
   '{protein,heat,maillard}'),
  ('julienne','Julienne cut','Knife Skills','medium',10,
   'Cut vegetables into thin, even matchsticks for fast, uniform cooking.',
   E'1. Square off the vegetable so it sits flat.\n2. Slice into thin planks (~3mm).\n3. Stack a few planks and slice again into matchsticks.\n4. Keep your guiding knuckles forward and the blade tip on the board. Evenness matters more than speed.',
   '{knife,prep,cuts}'),
  ('steaming','Steaming','Vegetables','easy',15,
   'Cook over simmering water with gentle moist heat that preserves nutrients and colour.',
   E'1. Bring an inch of water to a simmer under a steamer basket.\n2. Add vegetables in a single layer, cover, and steam until just tender.\n3. Check early — most greens need only 3-5 minutes.\n4. Season after, since steaming adds no salt of its own.',
   '{vegetables,moist-heat,healthy}'),
  ('caramelizing-onions','Caramelizing onions','Aromatics','easy',40,
   'Cook sliced onions low and slow until deeply golden and sweet.',
   E'1. Thinly slice onions and add to a wide pan with a little oil or butter over medium-low.\n2. Stir occasionally; let them go truly golden-brown, not just soft — 30-45 minutes.\n3. Deglaze with a splash of water if they stick.\n4. A pinch of salt early draws out moisture and speeds things along.',
   '{aromatics,low-and-slow}'),
  ('roasting','Roasting','Heat & Protein','easy',45,
   'Dry oven heat that browns the outside while cooking the inside through.',
   E'1. Heat the oven to 200-220C / 400-425F.\n2. Toss food with oil and salt; spread in a single layer so it roasts rather than steams.\n3. Give it room — a crowded tray traps moisture.\n4. Flip once halfway for even colour.',
   '{oven,vegetables,protein}'),
  ('sauteing','Sauteing','Heat & Protein','easy',10,
   'Quick-cook small pieces in a little fat over fairly high heat, keeping them moving.',
   E'1. Heat a wide pan and a little oil until shimmering.\n2. Add food in a single layer and toss or stir frequently.\n3. Keep the heat lively so things brown instead of stewing.\n4. Work in batches if the pan looks crowded.',
   '{heat,quick,stovetop}'),
  ('braising','Braising','Heat & Protein','medium',120,
   'Sear, then slow-cook in a little liquid until tender. Best for tough cuts.',
   E'1. Brown the meat hard on all sides, then remove.\n2. Soften aromatics in the same pot.\n3. Add liquid to come halfway up the meat, return it, cover, and cook low (oven or stovetop) until fork-tender.\n4. The collagen melts into the sauce — patience is the technique.',
   '{low-and-slow,braise,comfort}'),
  ('deglazing','Deglazing','Sauces','easy',5,
   'Lift the browned fond from a pan with liquid to build an instant sauce.',
   E'1. After searing, pour off excess fat, leaving the browned bits.\n2. Off heat, add a splash of stock, wine, or water.\n3. Scrape the bottom with a wooden spoon as it bubbles.\n4. Reduce, then finish with a knob of butter for shine.',
   '{sauce,fond,quick}'),
  ('mise-en-place','Mise en place','Prep','easy',15,
   'Prep and arrange every ingredient before the heat goes on.',
   E'Translating to "everything in its place," this is the habit that makes cooking calm. Measure, chop, and bowl up each component, and read the recipe through, **before** you start cooking. Fast recipes especially leave no time to chop mid-stream.',
   '{prep,organization,foundations}'),
  ('resting-meat','Resting meat','Heat & Protein','easy',10,
   'Let cooked meat sit before slicing so juices redistribute.',
   E'1. Pull meat from the heat a few degrees before target — it keeps rising (carryover).\n2. Tent loosely with foil and wait: 5 minutes for steaks, 15-20 for roasts.\n3. Slice against the grain for tenderness.',
   '{protein,rest,technique}'),
  ('toasting-spices','Toasting spices','Aromatics','easy',5,
   'Dry-toast whole or ground spices briefly to wake up their aroma.',
   E'1. Warm a dry pan over medium heat.\n2. Add spices and shake constantly until fragrant — 30-90 seconds.\n3. Tip out immediately so they do not scorch.\n4. Grind whole spices after toasting for the biggest flavour gain.',
   '{spices,aromatics,flavour}'),
  ('making-a-roux','Making a roux','Sauces','medium',10,
   'Cook equal parts fat and flour as the base for a smooth sauce or gravy.',
   E'1. Melt butter, whisk in an equal weight of flour.\n2. Cook, whisking, from blond (1-2 min) to brown depending on the dish.\n3. Add liquid gradually, whisking out lumps each time.\n4. Simmer to thicken and cook off the raw-flour taste.',
   '{sauce,thickening,foundations}'),
  ('poaching','Poaching','Heat & Protein','medium',15,
   'Cook gently in barely-simmering liquid for tender, delicate results.',
   E'1. Bring liquid (water, stock, milk) to 70-80C / 160-180F — just trembling, no rolling boil.\n2. Slip in eggs, fish, or chicken.\n3. Hold the gentle heat until just set.\n4. Season the poaching liquid well; it flavours from the outside in.',
   '{gentle,moist-heat,delicate}'),
  ('grilling','Grilling','Heat & Protein','medium',20,
   'Cook over direct high heat for char and smoke.',
   E'1. Get the grill properly hot and oil the grates.\n2. Set up two zones — hot for searing, cooler to finish thicker pieces.\n3. Let a crust form before turning so food releases cleanly.\n4. Rest grilled meats before serving.',
   '{grill,char,outdoor}')
on conflict (slug) do update set
  summary = excluded.summary,
  body = excluded.body,
  minutes = excluded.minutes,
  category = excluded.category,
  tags = excluded.tags;
