"use client";
import { useMemo, useState } from 'react';
import Link from 'next/link';
import foods from '@/lib/food-reference.json';
import { PageHeader } from '@/components/page-header';
import { FoodVisual } from '@/components/food-visual';
import { Button, Card, Input } from '@/components/ui';
import { prepRecipes } from '@/lib/prep-recipes';
import { RecipeDetail } from '@/components/recipe-detail';
import type { Recipe } from '@/lib/types';
export default function FoodGuidePage() {
  const [query,setQuery]=useState(''); const [limit,setLimit]=useState(12); const [open,setOpen]=useState<Recipe|null>(null);
  const results=useMemo(()=>foods.filter(food=>`${food.name} ${food.description}`.toLowerCase().includes(query.trim().toLowerCase())),[query]);
  return <div><PageHeader title="Food & nutrition guide" subtitle="Know what you are measuring. Exact foods, preparation states and source records, with useful ways to cook them."/>
    <Card className="mb-5"><h2 className="font-semibold">A small fridge, a useful cupboard</h2><div className="grid sm:grid-cols-3 gap-4 mt-3 text-sm"><div><h3 className="font-medium">Fresh · next three days</h3><p className="text-[var(--text-muted)] mt-1">Choose two meal bases. Buy their vegetables and protein in the quantities on your plan. Use delicate leaves and herbs first; keep garnishes separate.</p></div><div><h3 className="font-medium">Cupboard · replace as used</h3><p className="text-[var(--text-muted)] mt-1">Keep a compact set of lentils, beans, grains, oil and spices. Pick sauces that work in several meals. Follow the label after opening; many sauces need refrigeration.</p></div><div><h3 className="font-medium">Freezer · a buffer</h3><p className="text-[var(--text-muted)] mt-1">Freeze surplus portions promptly and label dates. Frozen vegetables let you add variety without committing to another fresh-food bag.</p></div></div><Link className="inline-flex min-h-11 items-center underline mt-2" href="/prep/">Build a three-day prep plan</Link></Card>
    <details className="mb-5 rounded-xl border border-[var(--border)] p-4"><summary className="cursor-pointer font-medium min-h-11">How to read these numbers</summary><p className="text-sm leading-relaxed">Values are per 100 g of the named edible food, not per portion. Raw, dry and cooked weights are different: cooking changes water content. Use the exact state in the recipe, weigh your amount, then divide the batch by its actual servings. Generic records will differ from your brand and preparation.</p><p className="text-sm mt-3">Recipe estimates omit optional ingredients and anything without a reliable match or weight conversion. An incomplete estimate is a subtotal, not a full meal total. Sodium, added sugar and allergens are not comprehensively covered here; check packaged-food labels. Recipe tags are not an allergen guarantee.</p><p className="text-xs mt-3">32 selected <a className="underline" href="https://fdc.nal.usda.gov/api-guide/" target="_blank" rel="noreferrer">USDA FoodData Central</a> SR Legacy records, retrieved September 21, 2026, public-domain CC0. These are historical reference averages, not laboratory measurements of your meal. Food illustrations are symbolic, not product photographs.</p></details>
    <Input aria-label="Search food references" placeholder="Search food or preparation, e.g. cooked lentils…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(12);}}/>
    <p role="status" className="text-sm text-[var(--text-muted)] my-3">{results.length} food references</p>
    <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{results.slice(0,limit).map(food=><Card key={food.id} className="space-y-3"><FoodVisual name={food.name}/><h2 className="font-semibold">{food.name}</h2><p className="text-xs text-[var(--text-muted)]">Per 100 g · {food.calories ?? '—'} kcal</p><div className="grid grid-cols-3 gap-2 text-center text-sm">{[['Protein',food.proteinG],['Fiber',food.fiberG],['Carbs',food.carbsG]].map(([label,value])=><div className="rounded-lg bg-[var(--bg)] p-2" key={String(label)}><strong className="block">{typeof value==='number'?`${Math.round(value*10)/10} g`:'—'}</strong><span className="text-xs text-[var(--text-muted)]">{label}</span></div>)}</div><details><summary className="min-h-11 flex items-center cursor-pointer text-sm underline">Food details & recipe ideas</summary><p className="text-xs leading-relaxed">{food.description}</p><p className="text-xs mt-2">Fat: {food.fatG ?? '—'} g / 100 g. A dash means unavailable, not zero.</p><a className="inline-flex min-h-11 items-center text-xs underline" target="_blank" rel="noreferrer" href={food.sourceUrl}>USDA source · FDC {food.id}</a>{prepRecipes.filter(r=>r.ingredients.some(i=>i.name.toLowerCase()===food.name.toLowerCase())).map(recipe=><button className="block text-left text-sm underline min-h-11" key={recipe.id} onClick={()=>setOpen(recipe)}>{recipe.name}</button>)}</details></Card>)}</div>
    {!results.length&&<p className="my-6">No exact reference in this collection. Try a shorter food name; don’t substitute an unrelated food’s nutrition.</p>}
    {results.length>limit&&<Button className="mt-5" variant="secondary" onClick={()=>setLimit(n=>n+12)}>Show 12 more</Button>}
    {open&&<RecipeDetail key={open.id} recipe={open} onClose={()=>setOpen(null)}/>}
  </div>;
}
